server:
  port: 9090
  
#undertow:
#   buffer-size: 1073741824
#   direct-buffers: 1073741824
#   io-threads: 100000
#   worker-threads: 100000
#   max-http-post-size: 1073741824    

management:
  security:  
    enabled: false 
    
spring:
  application:
    name: ignitenode
    profiles:
    active:
      default   
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    database-platform:  org.hibernate.dialect.PostgreSQL9Dialect
  datasource:
    url:  jdbc:postgresql://localhost:5432/ignite_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
 
  